### ISSUE TITLE
App Logo

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-content#34]
In data lists there should be a place to indicate the app's icon (both in app store format and within the app template). 
In the template, in lieu of the app "name" field, an image (png) should appear to create a more branded / customised experience for the user.

**Comment by esmeetewinkel** [comment]
The app icon (i.e. the image you press to enter an app that is installed on your phone) goes through a process in Android Studio, which we've not (yet) automated to go through spreadsheets. It's not been worth automating this since this doesn't change that often, and I'm happy to keep it manual for now - but let me know if you disagree. 

The images that display in the Google Play Store are uploaded to the Play Store directly, here there is no integrated process from our spreadsheets either. 

If you can populate the icon [here](https://docs.google.com/spreadsheets/d/1I5vNuScRfra-P9PCNaslzDJVUQwbvnhA/edit#gid=1804454691) I can subsequently do the manual processes. 
<img width="220" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74557272/5a0d28fe-10f2-4e2d-a927-961d98fc3c4c">

**Comment by lauriemarkle** [comment]
@esmeetewinkel -The logo / icon will also appear in lieu of the app name in the template, but our logo for FaciNK includes blue and has a white background. This is problematic because the header of the app is blue...can you change the header of the app to be white? 
<img width="201" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-content/assets/74552270/6d5636cd-728c-441c-b6cb-2f651e546d8e">

**Comment by esmeetewinkel** [comment]
@lauriemarkle The app's theming system is not yet established enough for me to easily change the app header colour, nor it to take an image input (currently it's always blue and only takes a string input, no images). However, this can be a good excuse for the developers to pick up some loose ends here. 

I would like to understand a bit better what you want. I think a white header above a white home screen will look a bit weird, how are you imagining this? Another suggestion would be for there to be a red-white version of the logo, appearing on the blue header background.
